services:
  - type: web
    runtime: node
    name: conecta-rock
    plan: free
    region: oregon
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: "*"
      - key: PUBLIC_SOCKET_URL
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: conecta-rock-db
          property: connectionString

databases:
  - name: conecta-rock-db
    plan: free
    region: oregon
    databaseName: conecta_rock
    user: conecta_rock
